FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --fix-missing
RUN apt-get install -y python3-pip swig
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

WORKDIR /usr/app
CMD python3 smac3_launcher.py