FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update 
RUN apt-get install -y python3-pip
RUN pip3 install numpy matplotlib
RUN apt-get install -y r-base
RUN Rscript -e "install.packages('irace', repos='https://cloud.r-project.org')"
WORKDIR /usr/app

CMD export PATH="$(Rscript -e "cat(paste0(system.file(package='irace', 'bin', mustWork=TRUE), ':'))" 2> /dev/null)${PATH}" && python3 irace_launcher.py